apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: crc-errors
  name: crc-errors
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: crc-errors
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: crc-errors
    spec:
      containers:
        - image: johncapobianco/merlin:crc_errors
          name: crc-errors
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
