apiVersion: batch/v1
kind: CronJob
metadata:
  name: deployment-restart
  namespace: default
spec:
  concurrencyPolicy: Forbid
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'bgp-process-vrf-all'
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'bgp-sessions'
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'interface-status'
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'inventory'
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'ip-int-brief'                   
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'ip-ospf'                
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'ip-route'
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'learned-acl'
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'learned-arp'
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'learned-bgp'
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'learned-config'
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'learned-interface'
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'learned-ospf'
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'learned-platform'
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'learned-routing'
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'learned-vlan'
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'learned-vrf'
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'mac-address-table'
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'port-channel-summary'                
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'version'
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'vlan'
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'vrf'                                  
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'bgp-check'                
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'crc-errors'
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'half-duplex'
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'ping-test'  
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment'
                - 'run-vs-start'                                                               