apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: ip-int-brief
  name: ip-int-brief
spec:
  type: NodePort
  ports:
    - name: "8095"
      port: 8095
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30015      
  selector:
    io.kompose.service: ip-int-brief
status:
  loadBalancer: {}
