apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: ip-route
  name: ip-route
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ip-route
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: ip-route
    spec:
      containers:
        - image: johncapobianco/merlin_kubernetes:ip_route
          name: ip-route
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
