apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: learned-vrf
  name: learned-vrf
spec:
  type: NodePort
  ports:
    - name: "8090"
      port: 8090
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30010      
  selector:
    io.kompose.service: learned-vrf
status:
  loadBalancer: {}
