apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: learned-interface
  name: learned-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: learned-interface
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: learned-interface
    spec:
      containers:
        - image: johncapobianco/merlin_kubernetes:learned_interface
          name: learned-interface
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
