apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: recommended-release
  name: recommended-release
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recommended-release
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: recommended-release
    spec:
      containers:
        - image: johncapobianco/merlin_kubernetes:recommended_release
          name: recommended-release
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
