apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: run-vs-start
  name: run-vs-start
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: run-vs-start
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: run-vs-start
    spec:
      containers:
        - image: johncapobianco/merlin:run_vs_start
          name: run-vs-start
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
